### PR TITLE
Add sms sharing

### LINKED ISSUE #157: SMS button sharing
I've seen the share-to-sms button on many websites.
can we try to implement it and display it instead of the tumblr button on mobile?

here's an article you might enjoy

http://weblog.west-wind.com/posts/2013/Oct/09/Prefilling-an-SMS-on-Mobile-Devices-with-the-sms-Uri-Scheme

### PR DESCRIPTION
**Pull request by endorama**
Close #157, adding sms sharing funcionality

The share button is still using the tumblr icons, @AmedeoSpagnolo could you take on with this?

Also, please test it on iOS :)

### CODE REVIEW

**Comment by marcoaimo** [comment]
unfortunately on ios it fill the receiver field (the green one in the screenshot) not the message body.

img_1346

**Comment by alemartina** [comment]
Hai verificato l'articolo che avevo postato?
ios richiede una sintassi diversa

On Wednesday, March 23, 2016, marco aimo <notifications@github.com> wrote:

> unfortunately on ios it fill the receiver field (the green one in the
> screenshot) not the message body.
>
> [image: img_1346]
> <https://cloud.githubusercontent.com/assets/6996492/13991929/3f50f564-f11a-11e5-9f6e-ab156f38a30d.PNG>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/todotoit/cryptoloji/pull/162#issuecomment-200416409>
>


-- 
Sent from my phone

**Comment by endorama** [comment]
Article has been reviewed and used. @marcoaimo could you please try to verify that the condition at [assets/js/states/share.js#L240](https://github.com/todotoit/cryptoloji/blob/enhancement-157/assets/js/states/share.js#L240) is met?

In order to properly work on ios the link created from the Sharer should begin with `sms:;body=[...]` while on android should begin with `sms:?body=[...]`

**Comment by endorama** [comment]
By the way, the same happens on my android. Seems like the `body` field is ignored.

**Comment by endorama** [comment]
Seems like the posted article was outdated. Is dated 2013, while it seems that around mid 2014 this functionality does no longer work.

From [different][1] [comments][2] and [replies][3] it seems that passing a body to the sms is not supported anymore. 

There is actually a [standard](https://tools.ietf.org/html/rfc5724) which should [be used as proposed](https://tools.ietf.org/html/rfc5724#section-2.5), but doesn't seem to be supported.

[1]: https://stackoverflow.com/questions/6480462/how-to-pre-populate-the-sms-body-text-via-an-html-link#comment33755022_20739615
[2]: https://stackoverflow.com/questions/6480462/how-to-pre-populate-the-sms-body-text-via-an-html-link#comment39658282_13138273
[3]: https://stackoverflow.com/a/6480533

**Comment by marcoaimo** [comment]
repost from @Giorgio-Olivero email.

New Feature: Enable Sharing Through SMS Text Messages With Po.st! |
Po.st Blog | The Most Advanced Social Sharing Platform

https://blog.po.st/enable-sharing-through-sms-text-messaging-with-po-st#qgJ5ezhbaiLdgk0T.97

**Comment by endorama** [comment]
It seems like the the article was really outdated. The new separator for iOS is `&` instead of `;`

@abusedmedia tested it and it works, leaving to @AmedeoSpagnolo for sms icon implementation

**Pull request merged**
